# Generated by Django 4.0.3 on 2022-08-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0007_user_subscribers_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_subscribers_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='user_subscribers_category',
            old_name='user_id',
            new_name='user',
        ),
    ]
