# Generated by Django 4.0.3 on 2022-08-25 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0009_rename_user_subscribers_category_usersubscriberscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 14, 54, 16, 237914)),
        ),
    ]
