# Generated by Django 4.0.3 on 2022-08-29 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0011_alter_post_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 8, 11, 38, 469098)),
        ),
    ]
